#!/bin/bash

if [ -z "$1" ]; then
  if [ $(nproc) -lt 4 ] ; then
    /app/vendor/bin/paratest --processes 4
  else
    /app/vendor/bin/paratest --processes $(nproc)
  fi;
else
  FIRST_SYMBOL=$(echo "$1" | cut -c1-1);

  if [ "$FIRST_SYMBOL" != "-" ]; then
    /app/vendor/bin/phpunit --filter "$1"
  else
    /app/vendor/bin/phpunit "$@";
  fi;
fi;
